apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm
  labels:
    {{- include "kafka-keycloak-realm.labels" . | nindent 4 }}
data:
  realm.yaml: |
    {{- include "kafka-keycloak-realm.realm" . | nindent 4 }}
